# Generated by Django 3.2.7 on 2021-09-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = []
