# Generated by Django 3.2.7 on 2021-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('league_year', models.IntegerField()),
                ('swid', models.CharField(max_length=50)),
                ('espn_s2', models.CharField(max_length=300)),
                ('league_name', models.CharField(default='<Name Missing>', max_length=50)),
            ],
        ),
    ]
