# Generated by Django 5.0 on 2024-07-25 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy_stats", "0002_leagueinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueinfo",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leagueinfo",
            name="espn_s2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="leagueinfo",
            name="swid",
            field=models.CharField(max_length=36),
        ),
    ]
