# Generated by Django 5.1.7 on 2026-01-07 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("num_teams", models.IntegerField(default=12)),
                (
                    "positions_included",
                    models.JSONField(
                        default=list,
                        help_text="List of positions to include (QB, RB, WR, TE, K, DST)",
                    ),
                ),
                (
                    "scoring_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Scoring multipliers for different stats",
                    ),
                ),
                ("is_draft_complete", models.BooleanField(default=False)),
                ("draft_started_at", models.DateTimeField(blank=True, null=True)),
                ("draft_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftedTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("player_id", models.CharField(max_length=50)),
                ("player_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=10)),
                (
                    "team",
                    models.CharField(help_text="NFL team abbreviation", max_length=10),
                ),
                ("fantasy_points", models.FloatField(default=0.0)),
                ("drafted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "draft_order",
                    models.IntegerField(help_text="Order in which player was drafted"),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafted_players",
                        to="playoff_pool.league",
                    ),
                ),
            ],
            options={
                "ordering": ["draft_order"],
                "unique_together": {("league", "player_id")},
            },
        ),
        migrations.CreateModel(
            name="LeagueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="playoff_pool.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "league")},
            },
        ),
    ]
