# Generated by Django 5.1.7 on 2026-01-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0002_alter_leaguemembership_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaguemembership",
            unique_together=set(),
        ),
    ]
