# Generated by Django 5.1.7 on 2026-01-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playoff_pool", "0003_alter_leaguemembership_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayoffDraftablePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("gsis_id", models.CharField(max_length=50)),
                ("player_id", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=200)),
                ("team", models.CharField(max_length=10)),
                ("position", models.CharField(max_length=10)),
                ("fantasy_points", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["position", "-fantasy_points"],
                "indexes": [
                    models.Index(
                        fields=["year", "position", "team"],
                        name="playoff_poo_year_1b4bc1_idx",
                    )
                ],
                "unique_together": {("year", "player_id")},
            },
        ),
    ]
