# Generated by Django 5.1.7 on 2026-01-09 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playoff_pool", "0004_playoffdraftableplayer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playoffdraftableplayer",
            unique_together={("year", "gsis_id")},
        ),
    ]
