# Generated by Django 5.1.7 on 2026-01-09 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playoff_pool", "0005_alter_playoffdraftableplayer_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="draftedteam",
            old_name="player_id",
            new_name="gsis_id",
        ),
        migrations.AlterUniqueTogether(
            name="draftedteam",
            unique_together={("league", "gsis_id")},
        ),
    ]
