# Generated by Django 5.1.7 on 2026-01-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0006_rename_player_id_draftedteam_gsis_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="draftedteam",
            old_name="team",
            new_name="nfl_team",
        ),
    ]
