# Generated by Django 5.1.7 on 2026-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0008_add_missing_user_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="roster_config",
            field=models.JSONField(
                default=dict,
                help_text="Roster configuration: {position: count, flex: {eligible_positions: [RB, WR, TE], count: 1}}",
            ),
        ),
    ]
