# Generated by Django 5.1.7 on 2026-01-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0009_league_roster_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueScoringSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_name",
                    models.CharField(
                        help_text="Name of the statistical category", max_length=100
                    ),
                ),
                (
                    "multiplier",
                    models.FloatField(
                        default=0.0, help_text="Point multiplier for this stat"
                    ),
                ),
                (
                    "is_defensive_stat",
                    models.BooleanField(
                        default=False, help_text="Whether this is a defensive/DST stat"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category grouping (passing, rushing, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for display",
                        max_length=100,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_scoring_settings",
                        to="playoff_pool.league",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "stat_name"],
                "indexes": [
                    models.Index(
                        fields=["league", "is_defensive_stat"],
                        name="playoff_poo_league__a8714a_idx",
                    )
                ],
                "unique_together": {("league", "stat_name")},
            },
        ),
    ]
