# Generated by Django 5.1.7 on 2026-01-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0010_leaguescoringsetting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playoffdraftableplayer",
            options={"ordering": ["position", "-draft_value"]},
        ),
        migrations.AddField(
            model_name="playoffdraftableplayer",
            name="draft_value",
            field=models.FloatField(default=0.0),
        ),
    ]
