# Generated by Django 5.1.7 on 2026-01-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0011_alter_playoffdraftableplayer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="league_year",
            field=models.IntegerField(
                default=2025, help_text="NFL season year for this league"
            ),
            preserve_default=False,
        ),
    ]
