# Generated by Django 5.1.7 on 2026-01-14 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playoff_pool", "0012_league_league_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gsis_id", models.CharField(db_index=True, max_length=50)),
                ("player_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=10)),
                ("nfl_team", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                (
                    "most_recent_game_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("most_recent_gametime", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["gsis_id"], name="playoff_poo_gsis_id_264f14_idx"
                    ),
                    models.Index(fields=["year"], name="playoff_poo_year_6995d3_idx"),
                ],
                "unique_together": {("gsis_id", "year")},
            },
        ),
        migrations.CreateModel(
            name="CachedPlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("game_type", models.CharField(max_length=10)),
                ("game_id", models.CharField(max_length=50)),
                (
                    "most_recent_game_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("most_recent_gametime", models.DateTimeField(blank=True, null=True)),
                (
                    "fantasy_points",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cached_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="playoff_pool.cachedplayers",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_stats",
                        to="playoff_pool.league",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["league"], name="playoff_poo_league__6b51f9_idx"
                    ),
                    models.Index(
                        fields=["cached_player"], name="playoff_poo_cached__dad0a3_idx"
                    ),
                    models.Index(fields=["week"], name="playoff_poo_week_e1985a_idx"),
                    models.Index(
                        fields=["game_id"], name="playoff_poo_game_id_01a1ef_idx"
                    ),
                    models.Index(
                        fields=["league", "cached_player"],
                        name="playoff_poo_league__000046_idx",
                    ),
                ],
                "unique_together": {("league", "cached_player", "game_id")},
            },
        ),
    ]
