# Generated by Django 5.1.7 on 2026-01-14 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playoff_pool", "0013_cachedplayers_cachedplayerstats"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="cachedplayerstats",
            table_comment="Optimized for fast lookups by league + cached_player",
        ),
    ]
