# Generated by Django 5.1.7 on 2026-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playoff_pool", "0014_alter_cachedplayerstats_table_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedplayerstats",
            name="is_eliminated",
            field=models.BooleanField(default=False),
        ),
    ]
