# Generated by Django 5.1.7 on 2025-09-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fantasy_stats",
            "0003_leagueinfo_created_date_alter_leagueinfo_espn_s2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueinfo",
            name="swid",
            field=models.CharField(max_length=100),
        ),
    ]
