# Generated by Django 5.1.7 on 2025-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy_stats", "0004_alter_leagueinfo_swid"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueinfo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
