# Generated by Django 5.1.7 on 2026-01-09 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy_stats", "0005_leagueinfo_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leagueinfo",
            options={"default_manager_name": "objects"},
        ),
    ]
