# Generated by Django 5.1.7 on 2026-04-10 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_stats", "0006_alter_leagueinfo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueinfo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leagues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
