name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    # - name: Django tests
    #   run: |
    #     python manage.py test
    - name: Pytest
      env:
        DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
        DATABASE_USERNAME : ${{secrets.DATABASE_USERNAME}}
        DATABASE_PASSWORD : ${{secrets.DATABASE_PASSWORD}}
        DATABASE_URL : ${{secrets.DATABASE_URL}}
        SECRET_KEY : ${{secrets.SECRET_KEY}}
        LEAGUE_ID : ${{secrets.LEAGUE_ID}}
        SWID : ${{secrets.SWID}}
        ESPN_S2 : ${{secrets.ESPN_S2}}
      run: |
        poetry run pytest
